Image:
    type: entity
    table: image
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        content:
            type: blob
            nullable: false
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
